#这些是受支持的融资模式平台

开源代码库: #替换为最多4个GitHub赞助商启用的用户名，例如[user1，user2]
帕特里翁: #替换为单个Patreon用户名
开放_集体: #替换为一个开放的集体用户名
高保真音响: #替换为单个Ko-fi用户名
潮汐电梯: #替换为一个Tidelift平台名称/包名称，例如npm/babel
社区_桥梁: #替换为单个社区桥项目名称，例如cloud-foundry
自由支付: #替换为一个Liberapay用户名
发行hunt: #替换为单个IssueHunt用户名
otechie: #替换为单个Otechie用户名
lfx _众筹: #替换为单个LFX众筹项目名称，例如cloud-foundry
习俗: #替换为最多4个自定义赞助网址，例如['link1 '，' link2']
